import type { OceanPreset, OceanPresetId } from './types';

/**
 * Named sea-state presets for quick comparison in the debug UI.
 * Mid-band amplitude 0.0012 ≈ 8 m peaks at heightScale 1 (see heightCalibration.ts).
 */
export const OCEAN_PRESETS: Record<OceanPresetId, OceanPreset> = {
  glassyMorning: {
    label: 'Glassy morning',
    spectrumModel: 'jonswap',
    amplitude: 0.00055,
    windSpeed: 4.5,
    windDirection: 10,
    fetch: 55_000,
    peakEnhancement: 1.9,
    directionalSpread: 14,
    smallWaveDamping: 0.048,
    choppiness: 0.18,
    heightScale: 0.85,
    timeScale: 0.65,
    enableSwell: false,
    enableDetail: false,
  },
  calmSea: {
    label: 'Calm sea',
    spectrumModel: 'jonswap',
    amplitude: 0.00075,
    windSpeed: 7,
    windDirection: 25,
    fetch: 95_000,
    peakEnhancement: 2.1,
    directionalSpread: 10.5,
    smallWaveDamping: 0.04,
    choppiness: 0.3,
    heightScale: 0.95,
    timeScale: 0.82,
    enableSwell: false,
    enableDetail: false,
  },
  longSwell: {
    label: 'Long swell',
    spectrumModel: 'jonswap',
    amplitude: 0.00115,
    windSpeed: 9,
    windDirection: 15,
    fetch: 950_000,
    peakEnhancement: 1.55,
    directionalSpread: 3.2,
    smallWaveDamping: 0.034,
    choppiness: 0.26,
    heightScale: 1.05,
    timeScale: 0.45,
    enableSwell: true,
    swellAmplitudeScale: 3.5,
    enableDetail: false,
  },
  heavySwell: {
    label: 'Heavy swell',
    spectrumModel: 'jonswap',
    amplitude: 0.00175,
    windSpeed: 8,
    windDirection: 20,
    fetch: 1_200_000,
    peakEnhancement: 1.45,
    directionalSpread: 2.6,
    smallWaveDamping: 0.036,
    choppiness: 0.24,
    heightScale: 1.2,
    timeScale: 0.4,
    enableSwell: true,
    swellAmplitudeScale: 5.5,
    enableDetail: false,
  },
  windySea: {
    label: 'Windy sea',
    spectrumModel: 'jonswap',
    amplitude: 0.0012,
    windSpeed: 15,
    windDirection: 40,
    fetch: 280_000,
    peakEnhancement: 3.2,
    directionalSpread: 5.5,
    smallWaveDamping: 0.019,
    choppiness: 0.48,
    heightScale: 1,
    timeScale: 1,
    enableSwell: false,
    enableDetail: false,
  },
  choppyLagoon: {
    label: 'Choppy lagoon',
    spectrumModel: 'jonswap',
    amplitude: 0.00105,
    windSpeed: 11,
    windDirection: 70,
    fetch: 32_000,
    peakEnhancement: 3.8,
    directionalSpread: 7.5,
    smallWaveDamping: 0.016,
    choppiness: 0.58,
    heightScale: 0.98,
    timeScale: 1.1,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 1.8,
  },
  openOcean: {
    label: 'Open ocean',
    spectrumModel: 'jonswap',
    amplitude: 0.00115,
    windSpeed: 14,
    windDirection: 35,
    fetch: 420_000,
    peakEnhancement: 2.8,
    directionalSpread: 4.5,
    smallWaveDamping: 0.022,
    choppiness: 0.42,
    heightScale: 1,
    timeScale: 0.95,
    enableSwell: true,
    swellAmplitudeScale: 2.5,
    enableDetail: true,
    detailAmplitudeScale: 1.4,
  },
  whitecaps: {
    label: 'Whitecaps',
    spectrumModel: 'jonswap',
    amplitude: 0.0012,
    windSpeed: 18,
    windDirection: 50,
    fetch: 175_000,
    peakEnhancement: 3.4,
    directionalSpread: 5.5,
    smallWaveDamping: 0.012,
    choppiness: 0.5,
    heightScale: 1.02,
    timeScale: 1.15,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 2,
  },
  gale: {
    label: 'Gale',
    spectrumModel: 'jonswap',
    amplitude: 0.00165,
    windSpeed: 22,
    windDirection: 48,
    fetch: 140_000,
    peakEnhancement: 3.9,
    directionalSpread: 4.8,
    smallWaveDamping: 0.014,
    choppiness: 0.68,
    heightScale: 1.08,
    timeScale: 1.08,
    enableSwell: false,
    enableDetail: false,
  },
  storm: {
    label: 'Storm',
    spectrumModel: 'jonswap',
    amplitude: 0.002,
    windSpeed: 26,
    windDirection: 55,
    fetch: 110_000,
    peakEnhancement: 3.7,
    directionalSpread: 5.2,
    smallWaveDamping: 0.013,
    choppiness: 0.7,
    heightScale: 1.12,
    timeScale: 1.05,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 1.6,
  },
};

/** Stable dropdown order from calm/glassy through storm. */
export const OCEAN_PRESET_IDS: OceanPresetId[] = [
  'glassyMorning',
  'calmSea',
  'longSwell',
  'heavySwell',
  'windySea',
  'choppyLagoon',
  'openOcean',
  'whitecaps',
  'gale',
  'storm',
];
