import type { OceanPreset, OceanPresetId } from './types';

/**
 * Named sea-state presets for quick comparison in the debug UI.
 * Presets are tuned for visible combined cascade range, not a strict Beaufort scale.
 */
export const OCEAN_PRESETS: Record<OceanPresetId, OceanPreset> = {
  glassyMorning: {
    label: 'Glassy morning',
    spectrumModel: 'jonswap',
    amplitude: 0.00058,
    windSpeed: 5.5,
    windDirection: 10,
    fetch: 45_000,
    peakEnhancement: 1.55,
    directionalSpread: 5.25,
    smallWaveDamping: 0.065,
    choppiness: 0.14,
    heightScale: 0.55,
    timeScale: 0.55,
    enableSwell: false,
    enableDetail: false,
  },
  calmSea: {
    label: 'Calm sea',
    spectrumModel: 'jonswap',
    amplitude: 0.0007,
    windSpeed: 7.5,
    windDirection: 25,
    fetch: 85_000,
    peakEnhancement: 1.85,
    directionalSpread: 4.5,
    smallWaveDamping: 0.05,
    choppiness: 0.24,
    heightScale: 0.68,
    timeScale: 0.75,
    enableSwell: false,
    enableDetail: false,
  },
  longSwell: {
    label: 'Long swell',
    spectrumModel: 'jonswap',
    amplitude: 0.0013,
    windSpeed: 9.5,
    windDirection: 15,
    fetch: 950_000,
    peakEnhancement: 1.55,
    directionalSpread: 3.2,
    smallWaveDamping: 0.034,
    choppiness: 0.26,
    heightScale: 0.7,
    timeScale: 0.45,
    enableSwell: true,
    swellAmplitudeScale: 1.4,
    enableDetail: false,
  },
  heavySwell: {
    label: 'Heavy swell',
    spectrumModel: 'jonswap',
    amplitude: 0.00185,
    windSpeed: 9,
    windDirection: 20,
    fetch: 1_200_000,
    peakEnhancement: 1.45,
    directionalSpread: 2.6,
    smallWaveDamping: 0.036,
    choppiness: 0.24,
    heightScale: 0.78,
    timeScale: 0.4,
    enableSwell: true,
    swellAmplitudeScale: 2,
    enableDetail: false,
  },
  windySea: {
    label: 'Windy sea',
    spectrumModel: 'jonswap',
    amplitude: 0.0012,
    windSpeed: 15,
    windDirection: 40,
    fetch: 280_000,
    peakEnhancement: 3.2,
    directionalSpread: 5,
    smallWaveDamping: 0.019,
    choppiness: 0.48,
    heightScale: 0.95,
    timeScale: 1,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 3.2,
  },
  choppyLagoon: {
    label: 'Choppy lagoon',
    spectrumModel: 'jonswap',
    amplitude: 0.00095,
    windSpeed: 12,
    windDirection: 70,
    fetch: 42_000,
    peakEnhancement: 2.9,
    directionalSpread: 5.2,
    smallWaveDamping: 0.022,
    choppiness: 0.62,
    heightScale: 0.88,
    timeScale: 1.15,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 3,
  },
  openOcean: {
    label: 'Open ocean',
    spectrumModel: 'jonswap',
    amplitude: 0.00125,
    windSpeed: 15,
    windDirection: 35,
    fetch: 420_000,
    peakEnhancement: 2.8,
    directionalSpread: 4.5,
    smallWaveDamping: 0.022,
    choppiness: 0.42,
    heightScale: 0.95,
    timeScale: 0.95,
    enableSwell: true,
    swellAmplitudeScale: 0.9,
    enableDetail: true,
    detailAmplitudeScale: 2.4,
  },
  whitecaps: {
    label: 'Whitecaps',
    spectrumModel: 'jonswap',
    amplitude: 0.00128,
    windSpeed: 18,
    windDirection: 50,
    fetch: 175_000,
    peakEnhancement: 3.4,
    directionalSpread: 4.8,
    smallWaveDamping: 0.012,
    choppiness: 0.5,
    heightScale: 1.03,
    timeScale: 1.15,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 4,
  },
  gale: {
    label: 'Gale',
    spectrumModel: 'jonswap',
    amplitude: 0.00168,
    windSpeed: 22,
    windDirection: 48,
    fetch: 140_000,
    peakEnhancement: 3.9,
    directionalSpread: 4.9,
    smallWaveDamping: 0.014,
    choppiness: 0.66,
    heightScale: 1,
    timeScale: 1.08,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 3.5,
  },
  storm: {
    label: 'Storm',
    spectrumModel: 'jonswap',
    amplitude: 0.00195,
    windSpeed: 26,
    windDirection: 55,
    fetch: 110_000,
    peakEnhancement: 3.7,
    directionalSpread: 5,
    smallWaveDamping: 0.013,
    choppiness: 0.7,
    heightScale: 1,
    timeScale: 1.05,
    enableSwell: false,
    enableDetail: true,
    detailAmplitudeScale: 4.5,
  },
};

/** Stable dropdown order from calm/glassy through storm. */
export const OCEAN_PRESET_IDS: OceanPresetId[] = [
  'glassyMorning',
  'calmSea',
  'longSwell',
  'heavySwell',
  'windySea',
  'choppyLagoon',
  'openOcean',
  'whitecaps',
  'gale',
  'storm',
];
